### ISSUE TITLE
Invalid status code: 400

### ISSUE THREAD

**Issue by jocull** [Frederikam/ukulele#73]
See
- https://github.com/lavalink-devs/lavaplayer/issues/69
- Which is fixed by https://github.com/lavalink-devs/lavaplayer/pull/70

This can be addressed by changing the implementation for lavaplayer to:

```
    // Use a commit version right after 2.1.0
    // See https://github.com/lavalink-devs/lavaplayer/pull/70
    implementation("com.github.lavalink-devs.lavaplayer:lavaplayer:727959e9f6")
```

Will work on a PR when I can.

**Comment by jocull** [comment]
I updated https://github.com/freyacodes/ukulele/pull/69 to include this fix as well

**Comment by jocull** [comment]
The PR has been updated, a Docker image is released. Initial feedback reports that this addresses the problem. I've moved to the proper release of lavaplayer as well instead of a commit hash 🙂

**Comment by kiloforce** [comment]
@jocull your ghcr.io/jocull/ukulele:jda-5 change appeared to be working last week, but this week getting a new error.  Likely YouTube changed something again?

```
2024-04-02 00:49:57.464  INFO 1 --- [atcher-worker-1] dev.arbjerg.ukulele.jda.CommandManager   : Invocation: ;play dnd ambient music
2024-04-02 00:49:58.142 ERROR 1 --- [back-1-thread-1] dev.arbjerg.ukulele.audio.Player         : Track exception

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Video returned by YouTube isn't what was requested
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:59) ~[lavaplayer-2.1.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[lavaplayer-2.1.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:83) ~[lavaplayer-2.1.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:44) ~[lavaplayer-2.1.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-2.1.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330) ~[lavaplayer-2.1.1.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
...
```

**Comment by jocull** [comment]
@kiloforce It seems like this is required upstream: https://github.com/lavalink-devs/lavaplayer/pull/93

In the meantime we can use the snapshot version from this repo. The branch and PR are updated. Docker images are also updated.

**Comment by kiloforce** [comment]
Thanks!

**Comment by Payden-Pringle** [comment]
I'm using` jocull/ukulele` at `jda-5:ffe3531` but still getting this error when trying to play a Youtube Video:
`Caused by: java.io.IOException: Invalid status code for video page response: 400`

**Comment by kiloforce** [comment]
@jocull  do you get the:

   "_Suspicious exception for playback of sHA_4wfQhE8 - com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in_"

error when trying to play music on Ukulele?

**Comment by jocull** [comment]
Yes, or a similar error. I will post an update to #77 with where I feel the situation is.
